### ISSUE TITLE
Keep a fast version upgrade by copying the `data.ms` when it's possible.

### ISSUE THREAD

**Issue by gmourier** [meilisearch/meilisearch-migration#10]
1. Make a dump
2. Store a hash of `/stats` response payload
3. Copy the data.ms to the new version binary folder
4. Compare the hash of the previous stats with the new MeiliSearch version hash stats payload.
5. If the hashes do not match, fall back to a dump import.

This allows being very using the data.ms instead of reindexing all documents with a dump when there are no breaking changes and to be able to fall back on the reindexing of a dump when it is not possible or in case of unexpected errors.

The script could even be smarter by comparing the major version of the old one with the new one. If it's different, we directly process a dump import because there are internal breaking changes with a circuit breaker.

**Comment by bidoubiwa** [comment]
> This allows being very using the data.ms instead of reindexing all documents with a dump when there are no breaking changes and to be able to fall back on the reindexing of a dump when it is not possible or in case of unexpected errors.

Per the migration of v0.22 to v.0.23 all documents where deleted when using the same `data.ms` between both versions. Would the hash have been the same or would it have been different?

**Comment by gmourier** [comment]
I guess it would have been detected with the hash but I don't think that's enough to guarantee that everything has been rewritten properly into the internal databases. 🤔  @irevoire

**Comment by alallema** [comment]
As this repo is now low-maintenance, I'm closing all issues that are not bugs

**Comment by irevoire** [comment]
Thanks @alallema, I realized that I never answered to gmourier so I’m going to do it but do not re-open the issue. It’s just for future reference.

> I guess it would have been detected with the hash but I don't think that's enough to guarantee that everything has been transferred properly to ensure an exact same state. 🤔

Yes, doing that only ensures that the « stats » database still works (which is like 1 in ~20 databases).
And since the stats database rarely change, there is a good chance that it’ll always work even if we can't even read a single document.
