### ISSUE TITLE
Auth Header check for migration.sh

### ISSUE THREAD

**Issue by aleixisp** [meilisearch/meilisearch-migration#23]
**Description**
Not a new feature, but some people might find it useful that `migration.sh` script checks the current version of meilisearch in order to make the API calls.

I would say to add to the readme to consider `nano migration.sh` and replace the header `Authorization: Bearer` by `X-Meili-API-Key` if the current version is lower than v0.25.0. That would be easier than adding the logic in the .sh to check for version and act accordingly. 

**Basic example**
To add in the readme, something like:
 If youru meilisearch service version is lower than v0.25.0 please modify the headers within `migration.sh` and replace `Authorization: Bearer` by `X-Meili-API-Key:`"

**Comment by alallema** [comment]
As this repo is now low-maintenance, I'm closing all issues that are not bugs
