### ISSUE TITLE
Improve `systemctl_status` function

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-migration#38]
TODO:
- [ ] Improve the naming function: add check context in function name, example: `check_systemctl_active_status`
- [ ] Simplify the function:
    - [ ] Remove `$callback2` that is useless
    - [ ] Add exit in any case when the service is not active
- [ ] Error message should be a parameter
- [ ] Change function calls with the correct parameters

**Comment by Pavan-Nambi** [comment]
hey can i work on this issue? @alallema

**Comment by alallema** [comment]
As this repo is now low-maintenance, I'm closing all issues that are not bugs.
