### ISSUE TITLE
Avoid using global variable in function

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-migration#39]
There are some functions where we use global variables instead of sending them as parameters. It is a best practice to avoid global variables in functions.
For example, in `delete_temporary_files` we use `dump_id`.

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please  assign it to me.

**Comment by alallema** [comment]
Hi @tarunsamanta2k20,
Thank you for being so interested 😃
We prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages volunteer contributors to open a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](URL).
We are looking forward to reviewing your PR. ❤️

**Comment by alallema** [comment]
As this repo is now low-maintenance, I'm closing all issues that are not bugs.
