### ISSUE TITLE
Avoid infinite loop

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-migration#45]
**Description:**
There is a risk of falling into an infinite loop [here](https://github.com/meilisearch/meilisearch-migration/blob/f75af79a94af8b6dea35f86c21a811e4cb679c63/scripts/update_meilisearch_version.sh#L281) of this script on this condition:
```bash
until curl -X GET 'http://localhost:7700/health' -s >/dev/null; do
```

**Solution:**
This condition has to be changed to check if the return of the curl request retrieves a `200 OK` HTTP code.
Check the example [this loop](https://github.com/meilisearch/meilisearch-migration/blob/f75af79a94af8b6dea35f86c21a811e4cb679c63/scripts/update_meilisearch_version.sh#L165), the return of the curl command is write in a file to check if there is any issue on the HTTP request.

**Comment by gokullan** [comment]
Hey there, I would like to work on this issue. Can it be assigned to me? The example you referenced had some `if - elif` conditionals. Do I need to incorporate those as well?

**Comment by brunoocasali** [comment]
Hi @gokullan you can tackle those issues! And yes I think you should introduce the new conditionals to prevent the infinite loop. 
CC: @alallema

**Comment by alallema** [comment]
>Hi @gokullan you can tackle those issues!

Yes !

> The example you referenced had some if - elif conditionals. Do I need to incorporate those as well?

Same thing as @brunoocasali I think so because you have to check the return of the curl retrieves request. unless you find another way to do that
