### ISSUE TITLE
Add a migration script that safely updates Meilisearch

### ISSUE THREAD

**Issue by RuslanAyaz** [meilisearch/meilisearch-migration#51]
**Description**
RP: https://github.com/meilisearch/meilisearch-migration/pull/50

Add a script for Meilisearch updates with the following advantages:
- the original version of Meilisearch remains intact: data, executable, and configuration files.
- simple rollback: bring up the original version of Meilisearch and switch ports in the Nginx server block.
- (optional) the Meilisearch instance can continue serving read queries during an updating process if you block all writes.

**Comment by alallema** [comment]
Has the PR associated with this issue has been closed I close the issue too
